[package]
name = "button"
version = "0.1.0"
edition = "2024"

[dependencies]
sdl2 = { version = "0.36", features = ["ttf"] }
reqwest = { version = "0.11", features = ["cookies", "json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
